# Generated by Django 2.1.5 on 2019-05-06 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aName', models.CharField(max_length=28)),
                ('aFamily', models.CharField(default='', max_length=50)),
                ('aFact', models.CharField(default='', max_length=1000)),
                ('aWeight', models.CharField(default='', max_length=28)),
                ('aLength', models.CharField(default='', max_length=28)),
                ('aLifespan', models.CharField(default='', max_length=50)),
                ('aFeature', models.CharField(default='', max_length=1000)),
                ('aPopulation', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iName', models.CharField(max_length=50)),
                ('iAnimal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP01.Animal')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latAnimal', models.FloatField(blank=True, default=None, null=True)),
                ('lonAnimal', models.FloatField(blank=True, default=None, null=True)),
                ('lAnimal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP01.Animal')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tName', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='aColor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='APP01.Color'),
        ),
        migrations.AddField(
            model_name='animal',
            name='aSize',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='APP01.Size'),
        ),
        migrations.AddField(
            model_name='animal',
            name='aType',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='APP01.Type'),
        ),
    ]
