# Generated by Django 2.1.7 on 2019-03-31 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='aDetail',
            field=models.CharField(default='hhhh', max_length=10000),
        ),
    ]
