# Generated by Django 2.1.5 on 2019-05-18 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP01', '0002_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='iAnimal',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
