# Generated by Django 2.1.5 on 2019-04-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP01', '0003_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='aHabitat',
            field=models.CharField(max_length=1000),
        ),
    ]
