# Generated by Django 2.1.5 on 2019-04-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP01', '0004_auto_20190404_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='aFamily',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='animal',
            name='aPopulation',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
