# Generated by Django 2.1.5 on 2019-04-05 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP01', '0005_auto_20190404_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='iName',
            field=models.CharField(max_length=50),
        ),
    ]
