# Generated by Django 2.1.5 on 2019-04-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP01', '0007_auto_20190407_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='aDetail',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='aHabitat',
        ),
        migrations.AddField(
            model_name='animal',
            name='aLength',
            field=models.CharField(default='', max_length=28),
        ),
        migrations.AddField(
            model_name='animal',
            name='aLifespan',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='animal',
            name='aWeight',
            field=models.CharField(default='', max_length=28),
        ),
    ]
