# Generated by Django 2.1.5 on 2019-04-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP01', '0008_auto_20190424_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='aFeature',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
